### ISSUE TITLE
やっぱりslim化したdocker imageだと表示できない

### ISSUE THREAD

**Issue by aaaaninja** [k1nPr45b0/docker-mdv#1]
>sudo docker run --rm -t -v $PWD/maskfile.md:/maskfile.md mdv.slim python terminal_markdown_viewer/mdv/markdownviewer.py /maskfile.md

```
Traceback (most recent call last):
  File "terminal_markdown_viewer/mdv/markdownviewer.py", line 1666, in <module>
    run()
  File "terminal_markdown_viewer/mdv/markdownviewer.py", line 1661, in run
    print(main(**kw) if PY3 else str(main(**kw)))
  File "terminal_markdown_viewer/mdv/markdownviewer.py", line 1409, in main
    raw = tags.code(raw.strip(), from_fenced_block=1, lang=lang)
  File "terminal_markdown_viewer/mdv/markdownviewer.py", line 725, in code
    s = style_ansi(raw_code, lang=lang)
  File "terminal_markdown_viewer/mdv/markdownviewer.py", line 540, in style_ansi
    lexer = get_lexer_by_name(lexer_alias(lang))
  File "/usr/local/lib/python2.7/site-packages/pygments/lexers/__init__.py", line 109, in get_lexer_by_name
    _load_lexers(module_name)
  File "/usr/local/lib/python2.7/site-packages/pygments/lexers/__init__.py", line 41, in _load_lexers
    mod = __import__(module_name, None, None, ['__all__'])
ImportError: No module named ruby
```

**Comment by aaaaninja** [comment]
`aaaaninja/mdv` の方なら問題なく表示してくれる.
